version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gestion-terranova-mongodb
    restart: always
    ports:
      - "27117:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - terranova-network

volumes:
  mongodb_data:
    driver: local

networks:
  terranova-network:
    driver: bridge
